# Generated by Codex on 2026-07-08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='phone',
            name='image',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='phone',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.7, max_digits=3),
        ),
        migrations.AddField(
            model_name='phone',
            name='short_description',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='phone',
            name='sold_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phone',
            name='specifications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='stock',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wheel_used', models.BooleanField(default=False)),
                ('reward_type', models.CharField(blank=True, choices=[('', 'No reward'), ('discount', '10% Discount Coupon'), ('shipping', 'Free Shipping')], max_length=20)),
                ('coupon_code', models.CharField(blank=True, max_length=24)),
                ('free_shipping', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
